# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{freya}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Duncan Grazier", "Paul Guelpa"]
  s.date = %q{2011-07-19}
  s.description = %q{Solr Ruby interface with connection proxying, efficient requests, and configurability.}
  s.email = %q{itsmeduncan@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "freya.gemspec",
    "lib/freya.rb",
    "lib/freya/client.rb",
    "lib/freya/configuration.rb",
    "lib/freya/connection.rb",
    "lib/freya/document.rb",
    "lib/freya/faceting/faceting.rb",
    "lib/freya/query_string.rb",
    "lib/freya/response.rb",
    "spec/freya/client_spec.rb",
    "spec/freya/configuration_spec.rb",
    "spec/freya/connection_spec.rb",
    "spec/freya/document_spec.rb",
    "spec/freya/faceting/faceting_spec.rb",
    "spec/freya/query_string_spec.rb",
    "spec/freya/response_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/rocketry/freya}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple Solr Ruby interface}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, ["= 0.8.7"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 2.3.11"])
      s.add_runtime_dependency(%q<json_pure>, ["= 1.4.6"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.4.1"])
      s.add_runtime_dependency(%q<will_paginate>, ["~> 2.3.15"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<mocha>, ["~> 0.9.12"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
    else
      s.add_dependency(%q<rake>, ["= 0.8.7"])
      s.add_dependency(%q<activesupport>, ["~> 2.3.11"])
      s.add_dependency(%q<json_pure>, ["= 1.4.6"])
      s.add_dependency(%q<nokogiri>, ["~> 1.4.1"])
      s.add_dependency(%q<will_paginate>, ["~> 2.3.15"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<mocha>, ["~> 0.9.12"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    end
  else
    s.add_dependency(%q<rake>, ["= 0.8.7"])
    s.add_dependency(%q<activesupport>, ["~> 2.3.11"])
    s.add_dependency(%q<json_pure>, ["= 1.4.6"])
    s.add_dependency(%q<nokogiri>, ["~> 1.4.1"])
    s.add_dependency(%q<will_paginate>, ["~> 2.3.15"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<mocha>, ["~> 0.9.12"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
  end
end

